chore: add test and format
CityOfZion/dora-sdk-ts pull request #1
Opened 2021-07-17 01:29 UTC by michael-siek

I would add more test but I was unsure of what args was required for `neo_legacy`

2021-07-19 17:05 UTC, lllwvlvwlll requested changes

2021-07-19 21:47 UTC, michael-siek commented on src/constants/index.ts
> +export const AXIOS_DORA = (version: string): AxiosInstance => {
@lllwvlvwlll do you mean that the api should look like `http://dora.coz.io/api/v2/neo2` and `http://dora.coz.io/api/v3/neo3`?

2021-07-20 21:28 UTC, lllwvlvwlll commented on src/constants/index.ts
> +export const AXIOS_DORA = (version: string): AxiosInstance => {
The endpoint is fine.  I just mean that the method should be like this: 
```ts
export const AXIOS_DORA = (protocol: string): AxiosInstance => {
  let endpoint: string = ''

  if (protocol=== neoLegacy') {
    endpoint = '/api/v1/neo2'
  } else if (protocol=== 'neo') {
    endpoint = '/api/v1/neo3'
  }

  return axios.create({
    baseURL: DORA_URL + endpoint
  })
}
```

:)

2021-07-20 21:29 UTC, michael-siek commented on src/constants/index.ts
> +export const AXIOS_DORA = (version: string): AxiosInstance => {
all changed and ready for review again :grin:

2021-07-20 21:33 UTC, michael-siek commented on src/constants/index.ts
> +export const AXIOS_DORA = (version: string): AxiosInstance => {
sorry its fixed now apparently changes don't happen when you don't push ¯\_(ツ)_/¯

2021-07-20 22:36 UTC, lllwvlvwlll approved these changes

2021-07-20 22:36 UTC, merged