chore: setup ESlint and fix lint lint errors
CityOfZion/dora-sdk-ts pull request #20
Opened 2023-07-14 00:45 UTC by Zidious

This PR sets up ESlint and fixes outstanding ESlint errors

2023-07-14 00:47 UTC, Zidious commented on src/api/neo/rest.ts
> +  ): Promise<any> {
Can this be types? Rather than `any`.

2023-07-14 00:47 UTC, Zidious commented on src/api/neo/rest.ts
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
Can this be types? Rather than `any`.

2023-07-14 00:47 UTC, Zidious commented on src/api/neo_legacy/rest.ts
> +  ): Promise<any> {
Same as above

2023-07-15 15:25 UTC, Zidious commented
/cc @ixje

2023-07-17 07:42 UTC, ixje commented
Note: I have a workshop to prepare and to finish some other tasks, but I'll get to this probably next week. Just wanted to let you know it will be looked at

2023-08-04 08:35 UTC, ixje requested changes
overall like the idea, just a couple of touch ups on the Neo 3 side and we should be good to go

2023-08-04 08:35 UTC, ixje commented on src/api/neo/rest.ts
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
Yes it can return https://github.com/CityOfZion/dora-sdk-ts/blob/560920622f88fa678ea74fd75b11ae02689f4ee4/src/interfaces/api/neo/responses.ts#L29

2023-08-04 08:35 UTC, ixje commented on src/api/neo/rest.ts
> +  ): Promise<any> {
Sure, but we don't have an interface for it yet. Here's a sample response
```
{"20230803":3,"20230804":4}
```
The keys are "YYYYMMDD" dates and the value is the total contract invocation count for that day. On the Dora frontend side the response is currently casted to the following
```ts
export type InvocationStat = {
  [date: string]: number
}
```

Note: there already exists a [InvocationStatsResponse](https://github.com/CityOfZion/dora-sdk-ts/blob/560920622f88fa678ea74fd75b11ae02689f4ee4/src/interfaces/api/neo/responses.ts#L95) but that is for a different endpoint (`invocationStats()`). So let's just call this `ContractStatsResponse`

2023-08-04 08:35 UTC, ixje commented on src/api/neo_legacy/rest.ts
> +  ): Promise<any> {
I'm hesitant to do anything on the the legacy side. I don't have a good idea where this is used, plus it's so old that I'd rather not require people to look at their legacy code again

2023-08-05 16:36 UTC, Zidious commented on src/api/neo_legacy/rest.ts
> +  ): Promise<any> {
Makes sense!

2023-08-05 16:48 UTC, Zidious commented on src/api/neo/rest.ts
> +import { DORA_URL } from '../../constants'
Apologies - formatting changes due to Prettier, will open another chore PR to amend these

2023-08-07 06:41 UTC, ixje approved these changes

2023-08-07 06:41 UTC, merged