Add Neo X REST client with getAddress support
CityOfZion/dora-sdk-ts pull request #28
Opened 2024-08-14 18:38 UTC by revett

@lllwvlvwlll mentioned that having the endpoints for the new Neo X API would be good.

This is provided by this node: https://github.com/CityOfZion/neox-blockscout

API docs are here if you're interested: https://eth.blockscout.com/api-docs

Keeping PRs small for now, this adds:

- Client class
- Support for get address

2024-08-14 18:45 UTC, revett commented on src/tests/api/NeoN3/neo.test.ts
>    it('should get the token provenance', async () => {
This test was failing in CI, not related to this PR.

I fixed the test so that this PR can be merged.

2024-08-24 08:03 UTC, ixje requested changes
I got just 2 requests. Feel free to merge after updating those

1. According to BlockScouts [Swagger file](https://github.com/blockscout/blockscout-api-v2-swagger/blob/main/swagger.yaml#L2301-L2304) the only required field in the `Address` response is `hash`, but your implementation has many more fields that are not optional. Please match the optional fields
2. The current sdk uses the shorthand optional style e.g. https://github.com/CityOfZion/dora-sdk-ts/blob/c62418c5ae1c34f8c57f5bfcf0b587f4de6219af/src/interfaces/api/neo_legacy/interface.ts#L98-L101
I think it's good to keep this style consistent now that we're early in capturing it.

2024-08-27 12:24 UTC, ixje commented on src/interfaces/api/neox/index.ts
> +  icon_url?: string
These are not optional according to
https://github.com/blockscout/blockscout-api-v2-swagger/blob/9ecd4569a800a0d06a6d05a99e68dbe0f7dc446f/swagger.yaml#L2920-L2921

2024-08-27 12:25 UTC, ixje approved these changes
I missed a tag previously. Will approve so it can be merged after update

2024-08-27 12:30 UTC, revett commented on src/interfaces/api/neox/index.ts
> +  icon_url?: string
Chatted via Discord, this is an old version of the code.

See: https://github.com/blockscout/blockscout-api-v2-swagger/blob/main/swagger.yaml

2024-08-27 12:31 UTC, merged